// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	redis2 "anilibrary-scraper/internal/domain/repository/redis"
	scraper2 "anilibrary-scraper/internal/domain/service/scraper"
	"anilibrary-scraper/internal/handler/http/api/v1/anime"
	"anilibrary-scraper/internal/handler/http/monitoring/healthcheck"
	"anilibrary-scraper/internal/scraper"
	"github.com/redis/go-redis/v9"
)

// Injectors from wire.go:

func MakeAnimeController(client *redis.Client) anime.Controller {
	animeRepository := redis2.NewAnimeRepository(client)
	scraperScraper := scraper.New()
	service := scraper2.NewScraperService(animeRepository, scraperScraper)
	controller := anime.NewController(service)
	return controller
}

func MakeHealthcheckController(client *redis.Client) healthcheck.Controller {
	controller := healthcheck.NewController(client)
	return controller
}
