linters-settings:
  govet:
    check-shadowing: true
    enable:
      - fieldalignment
  varnamelen:
    min-name-length: 2
    ignore-decls:
      - w http.ResponseWriter
      - r *http.Request

linters:
  enable:
    - exportloopref
    - revive
    - varnamelen
    - gci
    - goimports

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - govet
        - goimports