run:
  build-tags:
    - integration

output:
  sort-results: true

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - hugeParam # disabled until another architecture refactoring
  errcheck:
    check-type-assertions: true
  govet:
    enable:
      - fieldalignment
      - shadow
  varnamelen:
    min-name-length: 2
    ignore-decls:
      - w http.ResponseWriter
      - r *http.Request
      - i int

linters:
  enable:
    - decorder
    - errname
    - goconst
    - copyloopvar
    - revive
    - varnamelen
    - bodyclose
    - exhaustive
    - gocritic
    - importas
    - nakedret
    - noctx
    - prealloc
    - predeclared
    - gosec
    - stylecheck
    - unconvert
    - unparam
    - wastedassign
    - nolintlint
    - usetesting
    - tparallel
    - usestdlibvars

issues:
  fix: true