linters-settings:
  govet:
    check-shadowing: true
    enable:
      - fieldalignment
  varnamelen:
    min-name-length: 2
    ignore-decls:
      - w http.ResponseWriter
      - r *http.Request

linters:
  enable:
    - decorder
    - errname
    - goconst
    - exportloopref
    - revive
    - varnamelen
    - gci
    - bodyclose
    - exhaustive
    - gocritic
    - importas
    - nakedret
    - noctx
    - prealloc
    - predeclared

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - govet
  fix: true