version: "2"
linters:
  enable:
    - bodyclose
    - copyloopvar
    - decorder
    - errname
    - exhaustive
    - goconst
    - gocritic
    - gosec
    - importas
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - varnamelen
    - wastedassign
  settings:
    errcheck:
      check-type-assertions: true
    gocritic:
      disabled-checks:
        - hugeParam # disabled until another architecture refactoring
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    govet:
      enable:
        - fieldalignment
        - shadow
    varnamelen:
      min-name-length: 2
      ignore-decls:
        - w http.ResponseWriter
        - r *http.Request
        - i int
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - golines
  settings:
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
    golines:
      max-len: 120
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - config/config.go
issues:
  fix: true
output:
  sort-order:
    - linter
    - severity
    - file
run:
  build-tags:
    - integration
