version: '3.9'

volumes:
  redis-data:

services:
  app:
    container_name: anilibrary-request-parser
    build: .
    command:
      - "-pprof"
      - "-prom"
    volumes:
      - ./app/storage:/app/storage
    ports:
      - "8080:8080"
    networks:
      - local

  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD:-default}
    ports:
      - ${REDIS_PORT:-6380}:6379
    environment:
      REDIS_REPLICATION_MODE: master
    volumes:
      - redis-data:/data
    networks:
      - local

networks:
  local:
    driver: bridge