version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: anilibrary-scraper-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT:-6380}:6379
    environment:
      REDIS_REPLICATION_MODE: master
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a $$REDIS_PASSWORD ping | grep PONG"]
      interval: 2s
      timeout: 2s
      retries: 5
    volumes:
      - redis-data:/data
    networks:
      - local

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14269:14269"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:14269 || exit 1
      interval: 2s
      timeout: 2s
      retries: 5
    networks:
      - local

  app:
    depends_on:
      redis:
        condition: service_healthy
      jaeger:
        condition: service_healthy
    container_name: anilibrary-scraper
    build:
      context: .
      args:
        TIMEZONE: ${TIMEZONE:-Europe/Kiev}
    env_file:
      - .env
    volumes:
      - ./storage:/storage
    ports:
      - "8080:8080"
    networks:
      - local
      - shared

networks:
  local:
    driver: bridge
  shared:
    name: anilibrary
    external: true

volumes:
  redis-data: