version: '3.9'

services:
  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT:-6380}:6379
    environment:
      REDIS_REPLICATION_MODE: master
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a $$REDIS_PASSWORD ping | grep PONG"]
      interval: 2s
      timeout: 2s
      retries: 5
    volumes:
      - redis-data:/data
    networks:
      - local

  app:
    depends_on:
      redis:
        condition: service_healthy
    container_name: anilibrary-request-parser
    build: .
    command:
      - "-pprof"
      - "-prom"
    env_file:
      - .env
    volumes:
      - ./storage:/storage
    ports:
      - "8080:8080"
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
  redis-data: