version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: anilibrary-scraper-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT:-6380}:6379
    environment:
      REDIS_REPLICATION_MODE: master
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a $$REDIS_PASSWORD ping | grep PONG" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data
    networks:
      - local

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14269:14269"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:14269 || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - local

  filebeat:
    image: elastic/filebeat:${FILEBEAT_VERSION}
    container_name: anilibrary-scraper-filebeat
    profiles:
      - filebeat
    command:
      - -e
      - --strict.perms=false
    env_file:
      - .env
    volumes:
      - ./build/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./storage/logs:/logs
    networks:
      - shared

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: anilibrary-scraper-clickhouse
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    ports:
      - "8123:8123"
      - "9000:9000"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - local

  zookeeper:
    image: bitnami/zookeeper
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USER=${ZOOKEEPER_SERVER_USER}
      - ZOO_SERVER_PASSWORD=${ZOOKEEPER_SERVER_PASSWORD}
    ports:
      - "2181:2181"
    networks:
      - local

  kafka:
    depends_on:
      - zookeeper
    image: bitnami/kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_NUM_PARTITIONS=2
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions.sh --bootstrap-server localhost:9092" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "9092:9092"
    networks:
      - local

  app:
    depends_on:
      redis:
        condition: service_healthy
      jaeger:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      kafka:
        condition: service_healthy
    container_name: anilibrary-scraper
    build:
      context: .
      args:
        TIMEZONE: ${TIMEZONE:-Europe/Kiev}
    env_file:
      - .env
    volumes:
      - ./storage:/storage
    ports:
      - "8080:8080"
    networks:
      - local
      - shared

networks:
  local:
    driver: bridge
  shared:
    name: anilibrary
    external: true

volumes:
  redis-data:
  clickhouse-data: