version: '3.9'

services:
  app:
    container_name: anilibrary-request-parser
    build: .
    volumes:
      - ./app/storage:/app/storage
    ports:
      - "8080:8080"
    networks:
      - local

networks:
  local:
    driver: bridge