filebeat.autodiscover:
  providers:
    - type: docker
      hints:
        enabled: true
        default_config:
          enabled: false

output.logstash:
  hosts: '${FILEBEAT_OUTPUT}'
  username: '${FILEBEAT_USER}'
  password: '${FILEBEAT_PASSWORD}'