filebeat.inputs:
  - type: filestream
    id: anilibrary-scraper
    paths:
      - /logs/*.log
    parsers:
      - ndjson:
        overwrite_keys: true
        add_error_key: true
        expand_keys: true

output.logstash:
  hosts: ${FILEBEAT_OUTPUT}
  username: ${FILEBEAT_USER}
  password: ${FILEBEAT_PASSWORD}