// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package providers

import (
	redis2 "anilibrary-scraper/internal/domain/repository/redis"
	"anilibrary-scraper/internal/domain/service/scraper"
	"anilibrary-scraper/internal/handler/http/api/anime"
	"anilibrary-scraper/pkg/logger"
	"github.com/go-redis/redis/v9"
)

// Injectors from wire.go:

func WireScraperService(client *redis.Client) scraper.Service {
	animeRepository := redis2.NewAnimeRepository(client)
	service := scraper.NewScraperService(animeRepository)
	return service
}

func WireAnimeController(client *redis.Client, logger2 logger.Contract) anime.Controller {
	service := WireScraperService(client)
	controller := anime.NewController(logger2, service)
	return controller
}
