// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package providers

import (
	redis2 "anilibrary-scraper/internal/domain/repository/redis"
	"anilibrary-scraper/internal/domain/service/anime"
	anime2 "anilibrary-scraper/internal/handler/http/api/anime"
	"anilibrary-scraper/pkg/logger"
	"github.com/go-redis/redis/v9"
)

// Injectors from wire.go:

func WireScraperService(client *redis.Client) anime.ScraperService {
	animeRepository := redis2.NewAnimeRepository(client)
	scraperService := anime.NewScraperService(animeRepository)
	return scraperService
}

func WireAnimeController(client *redis.Client, logger2 logger.Contract) anime2.Controller {
	scraperService := WireScraperService(client)
	controller := anime2.NewController(logger2, scraperService)
	return controller
}
