apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" . }}-external-secret
  namespace: {{ include "namespace" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ include "app.fullname" . }}-secret-store
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: jwt.secret
    - secretKey: REDIS_ADDRESS
      remoteRef:
        key: redis.address
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: redis.password
    - secretKey: KAFKA_ADDRESS
      remoteRef:
        key: kafka.address
    - secretKey: KAFKA_CLIENT_USERS
      remoteRef:
        key: kafka.username
    - secretKey: KAFKA_CLIENT_PASSWORDS
      remoteRef:
        key: kafka.password
    - secretKey: KAFKA_TOPIC
      remoteRef:
        key: kafka.topic
    - secretKey: KAFKA_PARTITION
      remoteRef:
        key: kafka.partition
