apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-service
  namespace: {{ include "namespace" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
    {{- with .Values.app.service.ports }}
    - port: {{ .http }}
      targetPort: {{ $.Values.app.deployment.ports.http }}
      name: http
      protocol: TCP
    - port: {{ .monitoring }}
      targetPort: {{ $.Values.app.deployment.ports.monitoring }}
      name: monitoring
      protocol: TCP
    {{- end }}
