// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "anilibrary-scraper/internal/domain/dto"
	entity "anilibrary-scraper/internal/domain/entity"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockScraperService is a mock of ScraperService interface.
type MockScraperService struct {
	ctrl     *gomock.Controller
	recorder *MockScraperServiceMockRecorder
}

// MockScraperServiceMockRecorder is the mock recorder for MockScraperService.
type MockScraperServiceMockRecorder struct {
	mock *MockScraperService
}

// NewMockScraperService creates a new mock instance.
func NewMockScraperService(ctrl *gomock.Controller) *MockScraperService {
	mock := &MockScraperService{ctrl: ctrl}
	mock.recorder = &MockScraperServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScraperService) EXPECT() *MockScraperServiceMockRecorder {
	return m.recorder
}

// Process mocks base method.
func (m *MockScraperService) Process(ctx context.Context, dto dto.RequestDTO) (*entity.Anime, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", ctx, dto)
	ret0, _ := ret[0].(*entity.Anime)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Process indicates an expected call of Process.
func (mr *MockScraperServiceMockRecorder) Process(ctx, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockScraperService)(nil).Process), ctx, dto)
}
