basePath: /api/v1
definitions:
  request.ScrapeRequest:
    properties:
      url:
        type: string
    required:
    - url
    type: object
  response.Entry:
    properties:
      name:
        type: string
    type: object
  response.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  response.ScrapeResponse:
    properties:
      episodes:
        type: string
      genres:
        items:
          $ref: '#/definitions/response.Entry'
        type: array
      image:
        type: string
      rating:
        type: number
      status:
        type: string
      synonyms:
        items:
          $ref: '#/definitions/response.Entry'
        type: array
      title:
        type: string
      type:
        type: string
      voiceActing:
        items:
          $ref: '#/definitions/response.Entry'
        type: array
      year:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: Microservice for scraping anime data
  license:
    name: Boost Software License, Version 1.0
    url: https://github.com/VampireAotD/anilibrary-scraper/blob/main/LICENSE
  termsOfService: https://swagger.io/terms/
  title: Anilibrary Scraper
  version: "1.0"
paths:
  /anime/parse:
    post:
      consumes:
      - application/json
      description: Scrape anime data
      parameters:
      - default: Bearer
        description: Access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Url to scrape from
        in: body
        name: url
        required: true
        schema:
          $ref: '#/definitions/request.ScrapeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ScrapeResponse'
        "401":
          description: Unauthorized
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Scrape anime data
      tags:
      - anime
swagger: "2.0"
