name: security-checks
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run GoSec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
