name: tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version: ['1.21']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests
        run: go test -v ./... -race -count=1

      - name: Run integration tests
        run: go test -v ./test/... -tags=integration -race -count=1