name: Test

on:
  push:
    branches:
      - v1
  pull_request:
    branches:
      - v1

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests
        run: make test